import torch
import torch.nn as nn
import torch.nn.functional as F

# Inferred from UI (available to import in main.py)
CIN = 3
H = 32
W = 32

class GeneratedBlock(nn.Module):
    def __init__(self, in_channels=3):
        super().__init__()

    def forward(self, x):
        ys = []
        return x

class GeneratedModel(nn.Module):
    def __init__(self, in_channels=3):
        super().__init__()
        self.m_0 = nn.Conv2d(3, 64, kernel_size=7, stride=2, padding=3, groups=1, dilation=1, bias=False)
        self.m_1 = nn.BatchNorm2d(64)
        self.m_2 = nn.ReLU(inplace=True)
        self.m_3 = nn.MaxPool2d(kernel_size=3, stride=2)
        self.m_4 = nn.Conv2d(64, 64, kernel_size=3, stride=1, padding=1, groups=1, dilation=1, bias=False)
        self.m_5 = nn.BatchNorm2d(64)
        self.m_6 = nn.ReLU(inplace=True)
        self.m_7 = nn.Conv2d(64, 64, kernel_size=3, stride=1, padding=1, groups=1, dilation=1, bias=False)
        self.m_8 = nn.BatchNorm2d(64)
        self.m_9 = nn.Identity()
        self.m_10 = nn.ReLU(inplace=True)
        self.m_11 = nn.Conv2d(64, 64, kernel_size=3, stride=1, padding=1, groups=1, dilation=1, bias=False)
        self.m_12 = nn.BatchNorm2d(64)
        self.m_13 = nn.ReLU(inplace=True)
        self.m_14 = nn.Conv2d(64, 64, kernel_size=3, stride=1, padding=1, groups=1, dilation=1, bias=False)
        self.m_15 = nn.BatchNorm2d(64)
        self.m_16 = nn.Identity()
        self.m_17 = nn.ReLU(inplace=True)
        self.m_18 = nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1, groups=1, dilation=1, bias=False)
        self.m_19 = nn.BatchNorm2d(128)
        self.m_20 = nn.ReLU(inplace=True)
        self.m_21 = nn.Conv2d(128, 64, kernel_size=3, stride=1, padding=1, groups=1, dilation=1, bias=False)
        self.m_22 = nn.BatchNorm2d(64)
        self.m_23 = nn.Identity()
        self.m_24 = nn.ReLU(inplace=True)
        self.m_25 = nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1, groups=1, dilation=1, bias=False)
        self.m_26 = nn.BatchNorm2d(128)
        self.m_27 = nn.ReLU(inplace=True)
        self.m_28 = nn.Conv2d(128, 64, kernel_size=3, stride=1, padding=1, groups=1, dilation=1, bias=False)
        self.m_29 = nn.BatchNorm2d(64)
        self.m_30 = nn.Identity()
        self.m_31 = nn.ReLU(inplace=True)
        self.m_32 = nn.Conv2d(64, 256, kernel_size=3, stride=1, padding=1, groups=1, dilation=1, bias=False)
        self.m_33 = nn.BatchNorm2d(256)
        self.m_34 = nn.ReLU(inplace=True)
        self.m_35 = nn.Conv2d(256, 64, kernel_size=3, stride=1, padding=1, groups=1, dilation=1, bias=False)
        self.m_36 = nn.BatchNorm2d(64)
        self.m_37 = nn.Identity()
        self.m_38 = nn.ReLU(inplace=True)
        self.m_39 = nn.Conv2d(64, 256, kernel_size=3, stride=1, padding=1, groups=1, dilation=1, bias=False)
        self.m_40 = nn.BatchNorm2d(256)
        self.m_41 = nn.ReLU(inplace=True)
        self.m_42 = nn.Conv2d(256, 64, kernel_size=3, stride=1, padding=1, groups=1, dilation=1, bias=False)
        self.m_43 = nn.BatchNorm2d(64)
        self.m_44 = nn.Identity()
        self.m_45 = nn.ReLU(inplace=True)
        self.m_46 = nn.Conv2d(64, 512, kernel_size=3, stride=1, padding=1, groups=1, dilation=1, bias=False)
        self.m_47 = nn.BatchNorm2d(512)
        self.m_48 = nn.ReLU(inplace=True)
        self.m_49 = nn.Conv2d(512, 64, kernel_size=3, stride=1, padding=1, groups=1, dilation=1, bias=False)
        self.m_50 = nn.BatchNorm2d(64)
        self.m_51 = nn.Identity()
        self.m_52 = nn.ReLU(inplace=True)
        self.m_53 = nn.Conv2d(64, 512, kernel_size=3, stride=1, padding=1, groups=1, dilation=1, bias=False)
        self.m_54 = nn.BatchNorm2d(512)
        self.m_55 = nn.ReLU(inplace=True)
        self.m_56 = nn.Conv2d(512, 64, kernel_size=3, stride=1, padding=1, groups=1, dilation=1, bias=False)
        self.m_57 = nn.BatchNorm2d(64)
        self.m_58 = nn.Identity()
        self.m_59 = nn.ReLU(inplace=True)
        self.m_60 = nn.AdaptiveAvgPool2d(1)
        self.m_61 = nn.Linear(64, 10)

    def forward(self, x):
        ys = []
        x = self.m_0(x)
        ys.append(x)
        x = self.m_1(x)
        ys.append(x)
        x = self.m_2(x)
        ys.append(x)
        x = self.m_3(x)
        ys.append(x)
        x = self.m_4(x)
        ys.append(x)
        x = self.m_5(x)
        ys.append(x)
        x = self.m_6(x)
        ys.append(x)
        x = self.m_7(x)
        ys.append(x)
        x = self.m_8(x)
        ys.append(x)
        x = x + ys[8]  # Residual add
        ys.append(x)
        x = self.m_10(x)
        ys.append(x)
        x = self.m_11(x)
        ys.append(x)
        x = self.m_12(x)
        ys.append(x)
        x = self.m_13(x)
        ys.append(x)
        x = self.m_14(x)
        ys.append(x)
        x = self.m_15(x)
        ys.append(x)
        x = x + ys[15]  # Residual add
        ys.append(x)
        x = self.m_17(x)
        ys.append(x)
        x = self.m_18(x)
        ys.append(x)
        x = self.m_19(x)
        ys.append(x)
        x = self.m_20(x)
        ys.append(x)
        x = self.m_21(x)
        ys.append(x)
        x = self.m_22(x)
        ys.append(x)
        x = x + ys[22]  # Residual add
        ys.append(x)
        x = self.m_24(x)
        ys.append(x)
        x = self.m_25(x)
        ys.append(x)
        x = self.m_26(x)
        ys.append(x)
        x = self.m_27(x)
        ys.append(x)
        x = self.m_28(x)
        ys.append(x)
        x = self.m_29(x)
        ys.append(x)
        x = x + ys[29]  # Residual add
        ys.append(x)
        x = self.m_31(x)
        ys.append(x)
        x = self.m_32(x)
        ys.append(x)
        x = self.m_33(x)
        ys.append(x)
        x = self.m_34(x)
        ys.append(x)
        x = self.m_35(x)
        ys.append(x)
        x = self.m_36(x)
        ys.append(x)
        x = x + ys[36]  # Residual add
        ys.append(x)
        x = self.m_38(x)
        ys.append(x)
        x = self.m_39(x)
        ys.append(x)
        x = self.m_40(x)
        ys.append(x)
        x = self.m_41(x)
        ys.append(x)
        x = self.m_42(x)
        ys.append(x)
        x = self.m_43(x)
        ys.append(x)
        x = x + ys[43]  # Residual add
        ys.append(x)
        x = self.m_45(x)
        ys.append(x)
        x = self.m_46(x)
        ys.append(x)
        x = self.m_47(x)
        ys.append(x)
        x = self.m_48(x)
        ys.append(x)
        x = self.m_49(x)
        ys.append(x)
        x = self.m_50(x)
        ys.append(x)
        x = x + ys[50]  # Residual add
        ys.append(x)
        x = self.m_52(x)
        ys.append(x)
        x = self.m_53(x)
        ys.append(x)
        x = self.m_54(x)
        ys.append(x)
        x = self.m_55(x)
        ys.append(x)
        x = self.m_56(x)
        ys.append(x)
        x = self.m_57(x)
        ys.append(x)
        x = x + ys[57]  # Residual add
        ys.append(x)
        x = self.m_59(x)
        ys.append(x)
        x = self.m_60(x)
        ys.append(x)
        x = torch.flatten(x, 1)
        x = self.m_61(x)
        ys.append(x)
        return x